// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SelfLearning.Data;

#nullable disable

namespace SelfLearning.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251216204635_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SelfLearning.Domain.Entities.PassengerProfile", b =>
                {
                    b.Property<int>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("profile_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProfileId"));

                    b.Property<int?>("Age")
                        .HasColumnType("integer")
                        .HasColumnName("age");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("gender");

                    b.Property<string>("Interests")
                        .HasColumnType("text")
                        .HasColumnName("interests");

                    b.Property<string>("Preference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("preference");

                    b.Property<int>("ShareId")
                        .HasColumnType("integer")
                        .HasColumnName("share_id");

                    b.Property<string>("TravelPurpose")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("travel_purpose");

                    b.HasKey("ProfileId");

                    b.HasIndex("ShareId");

                    b.ToTable("passenger_profile");
                });

            modelBuilder.Entity("SelfLearning.Domain.Entities.PassengerTravelShare", b =>
                {
                    b.Property<int>("ShareId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("share_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ShareId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("message");

                    b.Property<int?>("PassengerId")
                        .HasColumnType("integer")
                        .HasColumnName("passenger_id");

                    b.Property<string>("Pnr")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("pnr");

                    b.Property<int>("TrainId")
                        .HasColumnType("integer")
                        .HasColumnName("train_id");

                    b.Property<DateOnly>("TravelDate")
                        .HasColumnType("date")
                        .HasColumnName("travel_date");

                    b.HasKey("ShareId");

                    b.HasIndex("TrainId");

                    b.ToTable("passenger_travel_share");
                });

            modelBuilder.Entity("SelfLearning.Domain.Entities.RouteStop", b =>
                {
                    b.Property<int>("RouteStopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("route_stop_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RouteStopId"));

                    b.Property<TimeOnly?>("ArrivalTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("arrival_time");

                    b.Property<TimeOnly?>("DepartureTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("departure_time");

                    b.Property<int>("SeqNo")
                        .HasColumnType("integer")
                        .HasColumnName("seq_no");

                    b.Property<int>("StationId")
                        .HasColumnType("integer")
                        .HasColumnName("station_id");

                    b.Property<int>("TrainId")
                        .HasColumnType("integer")
                        .HasColumnName("train_id");

                    b.HasKey("RouteStopId");

                    b.HasIndex("StationId");

                    b.HasIndex("TrainId", "SeqNo")
                        .IsUnique();

                    b.ToTable("route_stop");
                });

            modelBuilder.Entity("SelfLearning.Domain.Entities.Station", b =>
                {
                    b.Property<int>("StationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("station_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StationId"));

                    b.Property<string>("StationCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("station_code");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("station_name");

                    b.HasKey("StationId");

                    b.HasIndex("StationCode")
                        .IsUnique()
                        .HasFilter("\"station_code\" IS NOT NULL");

                    b.ToTable("station_master");
                });

            modelBuilder.Entity("SelfLearning.Domain.Entities.Train", b =>
                {
                    b.Property<int>("TrainId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("train_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TrainId"));

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("TrainName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("train_name");

                    b.Property<string>("TrainNo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("train_no");

                    b.HasKey("TrainId");

                    b.HasIndex("TrainNo")
                        .IsUnique();

                    b.ToTable("train_master");
                });

            modelBuilder.Entity("SelfLearning.Domain.Entities.PassengerProfile", b =>
                {
                    b.HasOne("SelfLearning.Domain.Entities.PassengerTravelShare", "Share")
                        .WithMany()
                        .HasForeignKey("ShareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Share");
                });

            modelBuilder.Entity("SelfLearning.Domain.Entities.PassengerTravelShare", b =>
                {
                    b.HasOne("SelfLearning.Domain.Entities.Train", "Train")
                        .WithMany()
                        .HasForeignKey("TrainId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Train");
                });

            modelBuilder.Entity("SelfLearning.Domain.Entities.RouteStop", b =>
                {
                    b.HasOne("SelfLearning.Domain.Entities.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SelfLearning.Domain.Entities.Train", "Train")
                        .WithMany()
                        .HasForeignKey("TrainId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Station");

                    b.Navigation("Train");
                });
#pragma warning restore 612, 618
        }
    }
}
